from stsriskcalc import STSRiskCalc

o = {
    "age": 50,
    "gender": "",
    "raceasian": "",
    "raceblack": "Yes",
    "racenativeam": "",
    "racnativepacific": "",
    "ethnicity": "",
    "payorprim": "",
    "payorsecond": "",
    "surgdt": "",
    "weightkg": "",
    "heightcm": "",
    "hct": "",
    "wbc": "",
    "platelets": "",
    "creatlst": "",
    "dialysis": "",
    "hypertn": "",
    "immsupp": "",
    "pvd": "",
    "cvd": "",
    "cvdtia": "",
    "cvdpcarsurg": "",
    "mediastrad": "",
    "cancer": "",
    "fhcad": "",
    "slpapn": "",
    "liverdis": "",
    "unrespstat": "",
    "syncope": "",
    "diabetes": "",
    "diabctrl": "",
    "infendo": "",
    "infendty": "",
    "cva": "",
    "cvawhen": "",
    "chrlungd": "",
    "cvdstenrt": "",
    "cvdstenlft": "",
    "ivdrugab": "",
    "alcohol": "",
    "pneumonia": "",
    "tobaccouse": "",
    "hmo2": "",
    "prcvint": "",
    "prcab": "",
    "prvalve": "",
    "prvalveproc1": "",
    "prvalveproc2": "",
    "prvalveproc3": "",
    "prvalveproc4": "",
    "prvalveproc5": "",
    "poc": "",
    "pocint1": "",
    "pocint2": "",
    "pocint3": "",
    "pocint4": "",
    "pocint5": "",
    "pocint6": "",
    "pocint7": "",
    "pocpci": "",
    "pocpciwhen": "",
    "pocpciin": "",
    "miwhen": "",
    "heartfailtmg": "",
    "classnyh": "",
    "cardsymptimeofadm": "",
    "carshock": "",
    "arrhythatrfib": "",
    "arrhythafib": "",
    "arrhythaflutter": "",
    "arrhyththird": "",
    "arrhythsecond": "",
    "arrhythsss": "",
    "arrhythvv": "",
    "medinotr": "",
    "medadp5days": "",
    "medadpidis": "",
    "medacei48": "",
    "medbeta": "",
    "medster": "",
    "medgp": "",
    "resusc": "",
    "numdisv": "",
    "stenleftmain": "",
    "laddiststenpercent": "",
    "hdef": "",
    "vdstena": "",
    "vdstenm": "",
    "vdinsufa": "",
    "vdinsufm": "",
    "vdinsuft": "",
    "vdaoprimet": "",
    "incidenc": "",
    "status": "",
    "iabpwhen": "",
    "cathbasassistwhen": "",
    "ecmowhen": "",
    "calculatedbmi": "",
    "procid": "8"
}

needed = []
for skip_key in o.keys():
    try:
        STSRiskCalc({key: value for key, value in o.items()
                     if key != skip_key}).calc_risks()
    except Exception as e:
        print(e, skip_key)
        needed.append(skip_key)

print(needed)
print(len(needed))
print(set(o.keys()).difference(set(needed)))
